apiVersion: v1
kind: Secret
metadata:
  name: ferrous-secrets
  namespace: ferrous-ci-cd
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "change-me-in-production"
  
  # JWT secret
  JWT_SECRET: "change-me-in-production"
  
  # Git SSH key (base64 encoded)
  # GIT_SSH_KEY: ""
  
  # S3 credentials (if using S3)
  # S3_ACCESS_KEY: ""
  # S3_SECRET_KEY: ""

